version: 2
machine:
  node:
    version: stable
jobs:
  build:
    docker:
      - image: circleci/node:12.4.0
      - image: circleci/postgres:9.6-alpine-ram

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: node .circleci/initdb.js
      - run: make test-full

